name = "Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "159b1072f358d27d79478f8ca4b9796cda110424d0e65a99fcf26ab5afec12bb"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
