name = "Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1b06fe65ca385bc5b01df1b92caafc92a76ed2d573f19105afb4432919342d8"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
