name = "Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d82adaee8306fc1d056cc9ef278554cd0a7f6598849fdc61d899363e0f1d5e11"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
