name: Build NTNH Lwjgl3ify Package

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Clone NTNH Repository
        run: |
          set -e
          git clone --depth=1 https://github.com/Nuclear-Tech-New-Horizons/NTNH.git

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Download lwjgl3ify
        run: |
          set -e
          version=$(curl -s https://api.github.com/repos/GTNewHorizons/lwjgl3ify/releases/latest | jq -r .tag_name)
          zip_url="https://github.com/GTNewHorizons/lwjgl3ify/releases/download/$version/lwjgl3ify-${version}-multimc.zip"
          jar_url="https://github.com/GTNewHorizons/lwjgl3ify/releases/download/$version/lwjgl3ify-${version}.jar"

          curl -L "$zip_url" -o lwjgl3ify-${version}-multimc.zip
          unzip -q lwjgl3ify-${version}-multimc.zip -d lwjgl3ify-multimc
          curl -L "$jar_url" -o lwjgl3ify-${version}.jar

      - name: Copy Contents
        run: |
          set -e
          version=$(curl -s https://api.github.com/repos/GTNewHorizons/lwjgl3ify/releases/latest | jq -r .tag_name)

          mkdir -p modpack/.minecraft
          cp -r NTNH/* modpack/.minecraft/

          cat > modpack/instance.cfg <<< "
            [General]
            name=NTNH
            iconKey=default
            InstanceType=OneSix
          "

          cp -r lwjgl3ify-multimc/patches modpack/
          cp -r lwjgl3ify-multimc/libraries modpack/
          cp -r lwjgl3ify-multimc/mmc-pack.json modpack/
          cp -r lwjgl3ify-${version}.jar modpack/.minecraft/mods

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NTNH-Lwjgl3ify
          path: modpack
          include-hidden-files: true
