name: Build and Release NTNH Packages

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version'
        required: true
        type: string
      changelog:
        description: 'Changelog'
        required: true
        type: string

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run lwjgl3ify Script
        run: |
          chmod +x ./build-scripts/build-lwjgl3ify.sh
          ./build-scripts/build-lwjgl3ify.sh

      - name: Run Prism Script
        run: |
          chmod +x ./build-scripts/build-prism.sh
          ./build-scripts/build-prism.sh

      - name: Run Native Script
        run: |
          chmod +x ./scripts/build-native.sh
          ./build-scripts/build-native.sh

      - name: Zip Files
        run: |
          zip -r "NTNH-${{ github.event.inputs.release_version }}-lwjgl3ify.zip" modpack-lwjgl3ify/
          zip -r "NTNH-${{ github.event.inputs.release_version }}-Prism.zip" modpack-prism/
          zip -r "NTNH-${{ github.event.inputs.release_version }}-Native.zip" modpack-native/

      - name: Create GitHub Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.event.inputs.release_version }}
          tag_name: ${{ github.event.inputs.release_version }}
          body: ${{ github.event.inputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            NTNH-${{ github.event.inputs.release_version }}-lwjgl3ify.zip
            NTNH-${{ github.event.inputs.release_version }}-Prism.zip
            NTNH-${{ github.event.inputs.release_version }}-Native.zip
